[tool.poetry]
name = "b10"
version = "0.1.0"
description = "b10 Python Package"
authors = ["naghipourfar <naghipourfar@berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
logging = "^0.4.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
