version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            pip install pytest
            PYTHONPATH=. poetry run pytest tests/

workflows:
  main:
    jobs:
      - build
